"""Stable serialized class identifiers for the Cyberdelia node pack."""

SAVE_IMAGE_NODE_CLASS = "CyberdeliaSaveImageWithMetaData"
CREATE_EXTRA_METADATA_NODE_CLASS = "CyberdeliaCreateExtraMetaData"

LEGACY_SAVE_IMAGE_NODE_CLASS = "SaveImageWithMetaData"
LEGACY_CREATE_EXTRA_METADATA_NODE_CLASS = "CreateExtraMetaData"

LEGACY_NODE_CLASS_MIGRATIONS = {
    LEGACY_SAVE_IMAGE_NODE_CLASS: SAVE_IMAGE_NODE_CLASS,
    LEGACY_CREATE_EXTRA_METADATA_NODE_CLASS: CREATE_EXTRA_METADATA_NODE_CLASS,
}
